CREATE DATABASE NOTIFICACION
GO
USE NOTIFICACION
GO

CREATE TABLE Estudiantes(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(40) NOT NULL,
Apellido VARCHAR(40) NOT NULL,
Cedula CHAR(11) NOT NULL UNIQUE,
Telefono CHAR(10) NOT NULL,
Fecha_N DATE NOT NULL,
Genero CHAR(1) NOT NULL,
Email VARCHAR(100) NOT NULL,
Estado CHAR(1) NOT NULL
)

GO

CREATE TABLE Usuarios(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nombre_Usuario VARCHAR(40) NOT NULL UNIQUE,
Pwd VARCHAR(40) NOT NULL,
Estado CHAR(1) NOT NULL
)

GO

CREATE TABLE Cursos(
Id INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(40) NOT NULL UNIQUE,
Estado CHAR(1) NOT NULL
)

GO

CREATE TABLE EstudianteCursos(
Id INT IDENTITY(1,1) PRIMARY KEY,
IdEstudiante INT NOT NULL,
IdCurso INT NOT NULL,
Nota INT
)

SELECT * FROM Estudiantes
SELECT * FROM Usuarios
SELECT * FROM Cursos
SELECT Id,IdEstudiante,IdCurso,Nota FROM EstudianteCursos
INSERT INTO Usuarios (Nombre_Usuario,Pwd,Estado) VALUES ('jhoanbaez','123456','A')
INSERT INTO Cursos (Nombre,Estado) VALUES ('SQL SERVER','A')
INSERT INTO Cursos (Nombre,Estado) VALUES ('PROGRAMACION C#','I')

SELECT * FROM EstudianteCursos