//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_ProgramacionCShearp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteCursos
    {
        public int Id { get; set; }
        public int IdEstudiante { get; set; }
        public int IdCurso { get; set; }
        public Nullable<int> Nota { get; set; }
    }
}
